### ISSUE TITLE
Support choice of images/videos in a single canvas

### ISSUE THREAD

**Issue by masaball** [samvera-labs/clover-iiif#108]
[Avalon Media System manifests](https://demo.avalonmediasystem.org/media_objects/pk02cb02n/manifest.json) use the `Choice` construct described in [Cookbook recipe 33](https://iiif.io/api/cookbook/recipe/0033-choice/) to provide users with quality options. Currently this is an unsupported feature in Clover that prevents Avalon manifests from loading properly: 
![Screenshot_20230209_094036](https://user-images.githubusercontent.com/68433277/217844970-4fbb0fab-52a3-41b4-8b0a-0260fd799cde.png)

Clover currently requests the manifest and loads the object metadata but fails to parse the `Body` to request the actual `.m3u8` file(s).

Even if there is no desire to provide full support for this, would it be possible to implement minimum handling to parse the `Choice` construct and request the first item in the list?

**Comment by hadro** [comment]
A +1 to this issue -- as we're working with the Internet Archive to update their IIIF infrastructure, including support for millions of A/V items, we're currently looking at using `choice` to handle the wide variety of files and derivatives that IA makes available for every A/V item. 

However, this means that most items don't seem to render when I try them using Clover.

Here's an example manifest that doesn't seem to work in clover for the reasons above (with the caveat that this is currently just a test URL and some elements are liable to change):
https://archivelabs-iiif-archivelab-org-presentation-v3.ux-fnf-misc.archive.org/iiif/3/HHFBC_tapes_D54A/manifest.json

**Comment by hadro** [comment]
FWIW, here's the production version of the manifest in the comment above: 
https://iiif.archive.org/iiif/HHFBC_tapes_D54A/manifest.json
And [this is what](https://samvera-labs.github.io/clover-iiif/docs/viewer/demo?iiif-content=https%3A%2F%2Fiiif.archive.org%2Fiiif%2FHHFBC_tapes_D54A%2Fmanifest.json) currently renders in the Clover interface

**Comment by mathewjordan** [comment]
@masaball cleaning up some old issues here and closing this. This is now supported. Thank you for opening the issue!
