### ISSUE TITLE
Clover Sliders Fetch the `id` of the `body` for Canvases

### ISSUE THREAD

**Issue by markpbaggett** [samvera-labs/clover-iiif#150]
Hello, 

Today while experimenting with A/V in Canopy, I noticed a problem that seems to be coming from Clover Sliders.  Whenever a thumbnail in a Clover Slider represents an A/V work, it attempts to fetch the `id` of the `body` of the `Canvas`.

Here is an example where you can see this (just look at the Network tab on the main page or any work page):

https://rfta-fall-2023.vercel.app/

You can also see it here:

https://dc.library.northwestern.edu/items/46394d80-6862-479a-bac1-e5486bc86723

**Comment by mathewjordan** [comment]
This has been resolved in https://github.com/samvera-labs/clover-iiif/pull/151
