### ISSUE TITLE
Use ImageViewer directly

### ISSUE THREAD

**Issue by rsimon** [samvera-labs/clover-iiif#162]
I have a use case where I have single images served via Image API manifests, but there is no Presentation API manifest associated. It looks like, internally, this is handled via the [ImageViewer](https://github.com/samvera-labs/clover-iiif/tree/main/src/components/Viewer/ImageViewer) component. But that doesn't seem to be exported from the library if I understand correctly.

Any recommendations on how to deal with such an Image-API-only scenario? I'd really love to use the Clover component rather than OpenSeadragon directly, due to the polished styling.

**Comment by adamjarling** [comment]
@rsimon Thanks for the comment.  This is on the Clover roadmap, experimenting with exporting underlying `Viewer` components.  Perhaps it's time to start building out a Roadmap for timing expectations for new features @mathewjordan ?

**Comment by mathewjordan** [comment]
@rsimon I don't think it would be too difficult to breakout exports of that component separately.

The ImageViewer component you reference has the prop `painting` (maybe poorly named) which would be an Annotation body. 

Ex: 

```json
{
  "id": "https://iiif.dc.library.northwestern.edu/iiif/2/c7e81825-e778-4ae1-b531-380d2dd24013/full/!640,807/0/default.jpg",
  "type": "Image",
  "format": "image/tiff",
  "width": 640,
  "height": 807,
  "service": [
    {
      "@id": "https://iiif.dc.library.northwestern.edu/iiif/2/c7e81825-e778-4ae1-b531-380d2dd24013",
      "@type": "ImageService2",
      "profile": "http://iiif.io/api/image/2/level2.json"
    }
  ]
}
```

The styled **OSD** component is a little more simplified and takes the resource URI in combination with the `imageType` as either _tiledImage_ or _simpleImage_. 

Of these two, which would be more useful for you?

**Comment by rsimon** [comment]
Hi @mathewjordan, 

so the resource URI would be the link to the image manifest (= ends with `info.json`)? In this case: yes, then the styled OSD component would probably be more useful. Although I could certainly manage with the ImageViewer component as well!

**Comment by alexandermirzoyan** [comment]
How we should import `ImageViewer` or `OSD` components?

**Comment by adamjarling** [comment]
Hi @rsimon @alexandermirzoyan  Have a look at https://samvera-labs.github.io/clover-iiif/docs/image as of this release last week.

https://github.com/samvera-labs/clover-iiif/releases/tag/v.2.6.0

Hopefully this gets you closer to something you might use?
