### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by jamiefolsom** [samvera-labs/clover-iiif#173]
It appears Clover is not localizable. 

See [here](https://github.com/samvera-labs/clover-iiif/blob/ed01ac9c0fc9c85aa7c732acf8199c27e4adbfc9/src/components/Viewer/Viewer/Toggle.tsx#L26) and [here](https://github.com/samvera-labs/clover-iiif/blob/ed01ac9c0fc9c85aa7c732acf8199c27e4adbfc9/src/components/Viewer/Viewer/Content.tsx#L60).

There aren't a ton of strings in the library. If we had time to add support for localized strings, would you consider a PR?

**Comment by mathewjordan** [comment]
Hi @jamiefolsom. Thank you for submitting. This is absolutely on our radar and we are prioritizing this in the coming month to support various locales as a replacement for the hardcoded language strings. Once I have structure in place, we'll include instructive documentation on how to best PR various locales.

Best - Mat

**Comment by jamiefolsom** [comment]
Cool, thanks for the update. We've had good luck with inlang paraglidejs for this. https://inlang.com/m/gerre34r/library-inlang-paraglideJs

**Comment by mathewjordan** [comment]
> Cool, thanks for the update. We've had good luck with inlang paraglidejs for this. https://inlang.com/m/gerre34r/library-inlang-paraglideJs

That looks quite nice. Thanks for the suggestion.

**Comment by mathewjordan** [comment]
Hi @jamiefolsom, I'd like to make you aware of i18n support in Clover now. We have begun replacing any hardcoded language using the `next-i18n` [package](https://www.i18next.com/). This is documented here:
https://samvera-labs.github.io/clover-iiif/docs/i18n

**Comment by jamiefolsom** [comment]
> Hi @jamiefolsom, I'd like to make you aware of i18n support in Clover now. We have begun replacing any hardcoded language using the `next-i18n` [package](https://www.i18next.com/). This is documented here:
> 
> https://samvera-labs.github.io/clover-iiif/docs/i18n

Fantastic, thanks very much for the update! We'll definitely try it out. We may be able to contribute some translations too (French in my case).
