### ISSUE TITLE
Ability to configure start Canvas ID

### ISSUE THREAD

**Issue by mikeapp** [samvera-labs/clover-iiif#174]
I have a use case for Clover as a Canvas selector UI.    It would be helpful if I could instantiate Clover and set the active Canvas based on ID.   For instance, if the last time the user looked at the particular Manifest they were on the third Canvas, I'd like to be able to create a new Clover instance in the same state.

**Comment by mathewjordan** [comment]
Hi @mikeapp. I'd personally love to complete this by supporting the Content State API at a more complex level. I believe a config property could also influence this, but we'd love to have the mechanics of this within Clover to lean on existing APIs.

Let me know your thoughts on this. 

Best - Mat

**Comment by tarjelavik** [comment]
Hi! I'd like this as well. A simple prop to set start canvas would be a nice low bar for IIIF newbies, in my opinion. Support for Content State API would be amazing, though :-).
Working on a new exhibition where i would like to use Clover for this use case.

**Comment by mikeapp** [comment]
@mathewjordan @tarjelavik  I submitted a PR https://github.com/samvera-labs/clover-iiif/pull/180 that *seems* not to break anything in the Viewer component.   It inspects the `iiifContent` property and matches some ContentState patterns - see the linked gist for what I tested.

**Comment by mathewjordan** [comment]
Resolved in #180
