### ISSUE TITLE
React v18: Invalid hook call

### ISSUE THREAD

**Issue by svenruegg** [samvera-labs/clover-iiif#69]
When using React 18 there is an „Invalid hook call“ showing up in the console.

https://reactjs.org/warnings/invalid-hook-call-warning.html

If you change the version in your sandbox example you can see it as well.

**Comment by mathewjordan** [comment]
Hi @svenruegg, thank you for noting this.

**Comment by mathewjordan** [comment]
Hi @svenruegg! Thank you again for issuing the React v18 update out. Clover IIIF should now work in 18.0 and be backwards compatible through 17.0 and to 16.13. See https://codesandbox.io/s/clover-react-v18-y2whrm?file=/src/App.js
