### ISSUE TITLE
Additional Configuration Options for OpenSeaDragon / Content Resource Viewer

### ISSUE THREAD

**Issue by markpbaggett** [samvera-labs/clover-iiif#75]
Hello,

I'm wondering if Clover could have a couple more configurable options via `options` or `customTheme`.  

First, I'd like to be able to customize the height of the image viewer beyond 450px.

This line defines the max height of the PlayerWrapper as 450px:
https://github.com/samvera-labs/clover-iiif/blob/d0df8463309c8f2c51829da59f476b44a06870c0/src/components/Player/Player.styled.tsx#L9

This line defines the height of Wrapper as 450px:
https://github.com/samvera-labs/clover-iiif/blob/d0df8463309c8f2c51829da59f476b44a06870c0/src/components/ImageViewer/ImageViewer.styled.tsx#L34

I'm not sure which is the culprit, but I'd love it if this was customizable through the JSX rather than needing to be handled via CSS.

Additionally, I'd love to be able to modify the options or custom theme to allow the OpenSeaDragon background to be something besides black.

Let me know if you need more clarification or better details.

**Comment by mathewjordan** [comment]
Thanks @markpbaggett, this makes a lot of sense and should functionally be rather simple to implement. 

For height, we'll likely still want some hardcoded default, yet providing it the ability either be `unset` and stretch to the height of a container or be another set value passed in would be a pretty nice feature.

**Comment by mathewjordan** [comment]
v1.10.1 should handle this for you now @markpbaggett. The two new options added, `canvasBackgroundColor` and `canvasHeight`, correlate to CSS `background-color` and `height` properties respectively.

https://github.com/samvera-labs/clover-iiif#reference
