### ISSUE TITLE
Collections

### ISSUE THREAD

**Issue by HemboPagi** [samvera-labs/clover-iiif#76]
Hi, does clover-iif supports collections?

I tested my manifest (https://cms.rahvaroivad.ee/wp-json/iiif/manifest/gallery/172) on your demo page and it did not work.
Same manifest with Mirador works : https://projectmirador.org/embed/?iiif-content=https://cms.rahvaroivad.ee/wp-json/iiif/manifest/gallery/172

All the best
hembo

**Comment by mathewjordan** [comment]
Hi @HemboPagi. 

Clover's main intention is a as an items/canvas viewer for IIIF resources that are `"type": "Manifest"`.  It does not currently support a Collection in the same way UV and Mirador do. Thanks for your thoughts, as that type of Manifest selection functionality could be a feature at some point.

We are currently working on a companion component Bloom IIIF https://github.com/samvera-labs/bloom-iiif which is intended for `"type": "Collection"`. I tested your collection ID in that and it seems to render well, though Bloom does render better if the items contain a thumbnail.

Hope this is helpful.

Best,
Mat
