### ISSUE TITLE
Openseadragon config options is not picked up. 

### ISSUE THREAD

**Issue by JoshBone** [samvera-labs/clover-iiif#96]
Hi,

It's said in the documentation, that Openseadragon config options can be passed with the options object. 
Checking the source code, after it didn't work for me, it seems that this part is not implemented yet, OSD config is pre-defined:
https://github.com/samvera-labs/clover-iiif/blob/6eaebbab8a30c2fa5241bc50d5f35bb6484bbca9/src/components/ImageViewer/OSD.tsx#L27-L43

Would you need some help implementing this, or are you working on it now?
The same question goes for the FullScreen option. 

Thank you for your amazing work on this!

**Comment by mathewjordan** [comment]
Hi @JoshBone, and thanks for inputting the issue.

You're absolutely correct. This is not working, though, I do think it was intended to at some point given the documentation passage.

I'd be happy to work with you on creating this functionality or handling it myself. Options themself will be stored in the React context at https://github.com/samvera-labs/clover-iiif/blob/main/src/context/viewer-context.tsx#L51. It should be pretty easy to take values set within this and spread them into the config that is predefined in OSD.tsx. This would be the first step, then other more specific overriding might follow.

```jsx
const viewerState = useViewerState();
const { configOptions } =  viewerState;

const config = {
    id: `openseadragon-viewport-${instance}`,
    loadTilesWithAjax: true,
    homeButton: "zoomReset",
    showFullPageControl: false,
    zoomInButton: "zoomIn",
    zoomOutButton: "zoomOut",
    showNavigator: true,
    navigatorBorderColor: "transparent",
    navigatorId: `openseadragon-navigator-${instance}`,
    gestureSettingsMouse: {
      clickToZoom: true,
      dblClickToZoom: true,
      pinchToZoom: true,
      scrollToZoom: false,
    },
    ...configOptions.openSeadragon
  };

```

I'll dig in a little, but please put forward a PR if you have thoughts.

**Comment by mathewjordan** [comment]
@JoshBone Sorry for the delay. This should be resolved at this point.
